server:
  port: 8083
spring:
  application:
    name: hrpq-matricula-service

  # Configuración de la base de datos H2
  datasource:
    url: jdbc:h2:mem:hrpq-matricula;DB_CLOSE_DELAY=-1  # Usar base de datos en memoria
    username: sa  # Usuario por defecto para H2
    password:   # Contraseña por defecto para H2
    driver-class-name: org.h2.Driver  # Controlador H2

  # JPA Hibernate configuración
  jpa:
    hibernate:
      ddl-auto: update  # Actualiza las tablas si es necesario
    show-sql: true  # Muestra las consultas SQL en los logs

  # H2 console web
  h2:
    console:
      enabled: true  # Habilitar la consola web de H2
      path: /h2-console  # URL para acceder a la consola H2 en el navegador

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost
